### ISSUE TITLE
ForEach as content only creates 1 view in views array

### ISSUE THREAD

**Issue by JaydenIrwin** [GeorgeElsham/ViewExtractor#2]
After further experimentation with this package, I noticed using a ForEach() as the content view will only create 1 view in the views array regardless of how many views the ForEach contains. The ViewExtractor should be expanded to allow it to get the views from a ForEach.

By the way, great package! You can see it in use here: [https://github.com/JaydenIrwin/CircularStackKit](https://github.com/JaydenIrwin/CircularStackKit)

**Comment by GeorgeElsham** [comment]
I really appreciate this feedback! I have now implemented it in release `1.0.4`. Sorry for the (potentially) code-breaking changes that may occur since this package is new. Also, remember to refer to the example again in the README and make sure to use **both** initializers otherwise the new `ForEach` feature may not appear to work.

Thank you!
